### ISSUE TITLE
Add images in the post body

### ISSUE THREAD

**Issue by wahyusaputra** [tinacms/tina-starter-grande#57] opened 2020-06-10 09:28 UTC
Currently there is no functionality to add images in the body of a post. I think this is an awesome feature to be added because most of the time we would like to add images when writing a blog post.

Many thanks in advance.

**Comment by kendallstrautman** [comment] 2020-06-12 15:56
Duplicate of #24

**Closed by kendallstrautman** 2020-06-12 15:56 UTC
